M48
; DRILL file {KiCad 7.0.10} date Sat Mar 23 21:53:36 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-23T21:53:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0906
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2835
%
G90
G05
T1
X2.72Y-2.8964
T2
X2.719Y-3.879
M30
