M48
; DRILL file {KiCad 7.0.10} date Sun Mar 24 11:08:14 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-24T11:08:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.5934Y-3.0417
X1.7666Y-3.0417
T2
X1.275Y-1.77
X1.275Y-3.175
X1.9682Y-1.3987
X2.9918Y-1.3987
X3.675Y-1.77
X3.675Y-3.175
M30
